version: "3"

services:
  postgres:
    image: "postgres:12"
    ports:
      - "5432:5432"
  redis:
    image: "redis:6"
    ports:
      - "6379:6379"
  nginx:
    restart: always
    build:
      context: "./nginx"
      dockerfile: "Dockerfile.dev"
    ports:
      - "3050:80"
  api:
    build:
      context: "./api"
      dockerfile: "Dockerfile.dev"
    volumes:
      - "/app/node_modules"
      - "./api:/app"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres
      - PGPORT=5432
    ports:
      - "4000:4000"
  client:
    build:
      context: "./client"
      dockerfile: "Dockerfile.dev"
    volumes:
      - "/app/node_modules"
      - "./client:/app"
    ports:
      - "3000:3000"
